services:
  api:
    build:
      context: ./API/ForumApi
    ports:
      - "5000:5000"
    networks:
      - forumnetwork
    depends_on:
      - db
  client:
    build:
      context: ./client
    ports:
      - "4200:4200"
    networks:
      - forumnetwork
  db:
    image: postgres:12.16-bullseye
    ports:
      - "5432:5432"
    networks:
      - forumnetwork
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password

networks:
  forumnetwork: